### PR TITLE
Fixing "Toggle Progress" For RTL Support & correct display & Fixing Translate

### PR DESCRIPTION
**Pull request by amirroox**
# Problem
toggle progress is not displayed well in RTL.
It opens, but does not close.
It also doesn't look good.

# Change
Fixing "Toggle Progress" For RTL Support

# File Edit
- [x] src/components/LearnProgress.tsx

### CODE REVIEW

**Comment by amirroox** [comment]
# Problem
Fix correct display (upside down) of regex in RTL (in CheatSheet, playground, learning Part )

# Change
Fix correct display of regex in RTL

# File Edit
- [x] src/components/Step.tsx
- [x] src/components/CheatSheetCollapse.tsx

**Comment by amirroox** [comment]
# Problem
Translation problem in lesson 49 of Persian language

# Change
Fixing Persian Translate For lesson 49

# File Edit
- [x] src/localization/fa/learn.json

**Comment by amirroox** [comment]
I apologize if I did not create a separate brunch. 😓💔
@aykutkardas

**Review by aykutkardas — APPROVED** [review]

**Comment by aykutkardas** [comment]
Thanks for your contribution. ❤️

**Pull request merged**
