### PR TITLE
feature: add feature to serviceworker

### LINKED ISSUE #12: Add PWA support
This site must be available as an app. That's why adding PWA support is important.

### PR DESCRIPTION
**Pull request by LuizHAP**
Fix #12 using serviceworker 

ZxZ7XQhHUf

### CODE REVIEW

**Comment by aykutkardas** [comment]
> @aykutkardas fixed

Why do we need an offline html page?

**Comment by LuizHAP** [comment]
> > @aykutkardas fixed
> 
> Why do we need an offline html page?


Offline page is used when you have a PWA, it is necessary when the person who is using your project is without internet. So, instead of returning a page not found, it would return that page. But if you want, I can remove it. What do you prefer?

**Comment by aykutkardas** [comment]
> Offline page is used when you have a PWA, it is necessary when the person who is using your project is without internet. So, instead of returning a page not found, it would return that page. But if you want, I can remove it. What do you prefer?

Actually, my goal with PWA is to cache the page and make it available offline if users have visited the page before. Because once installed, there is no need for internet to be used.

**Comment by aykutkardas** [comment]
Does this file use? @LuizHAP 
`registerServiceWorker.js `

**Comment by LuizHAP** [comment]
> Does this file use? @LuizHAP `registerServiceWorker.js `

I forgot to remove. Any changes?

**Comment by aykutkardas** [comment]
I took care of this myself and found that it works as expected like this. 

https://github.com/aykutkardas/regexlearn.com/commit/de0d80e3c3922ed45a72891bdbc3849a8de55e34

Thank you for your help. @LuizHAP

**Comment by LuizHAP** [comment]
@aykutkardas This pull request has been submitted to a participating repository but has not yet been accepted by a maintainer. A PR can be accepted either by being merged, having an approving review, or being given the ‘hacktoberfest-accepted’ label.

**Pull request closed without merging**
